version: '3'

services:
  server:
    image: 'rjdeck/bitcoin-cornjob'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '5000:5000'
    environment:
      - DATABASE_USER_URL=${DATABASE_USER_URL}
      - DATABASE_TX_URL=${DATABASE_TX_URL}
      - BLOCKCHAIR_API_KEY=${BLOCKCHAIR_API_KEY}
    volumes:
      - './:/app'